services:
  mongodb:
    image: mongo:latest
    container_name: cloudcost-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: cloudcost-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cloudcost_wise
      - NODE_ENV=development
      - JWT_SECRET=HUHAUSHAUQWASJNADDSDWDWFSSFSA
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: cloudcost-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: