apiVersion: v1
kind: Namespace
metadata:
  name: cloudcost
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudcost-secrets
  namespace: cloudcost
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://Cloud_Cost:Dhanesh6547@cloudcost.3nvxr0g.mongodb.net/?appName=CloudCost"
  JWT_SECRET: "HUHAUSHAUQWASJNADDSDWDWFSSFSA"